import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

import { AuthProvider } from "../components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
          {/* Header */}
          <header className="bg-indigo-600 text-white shadow-md">
            <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
              <h1 className="text-xl font-semibold">Мій Додаток</h1>
              <nav>
                <ul className="flex space-x-6">
                  <li>
                    <a href="/" className="hover:underline">
                      Головна
                    </a>
                  </li>
                  <li>
                    <a href="/dashboard" className="hover:underline">
                      Dashboard
                    </a>
                  </li>
                  <li>
                    <a href="/register" className="hover:underline">
                      Вхід
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
          </header>

          <main className="flex-grow max-w-7xl mx-auto px-4 py-8 w-full">
            {children}
          </main>

          <footer className="bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400 py-4 mt-auto">
            <div className="max-w-7xl mx-auto px-4 text-center text-sm">
              © {new Date().getFullYear()} TO DO.
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
